theme: jekyll-theme-slate
title: Numerical Methods
description: First numerical methods course for geoscience undergraduates
name1: Matthew Piggott
address1: Room 4.82, Royal School of Mines
email1: m.d.piggott@imperial.ac.uk
github_username1:  matt-piggott
